In [1]:
import numpy as np
import itertools


In [2]:
def wlasnosc_ograniczonej_przestrzeni_dla_podzbiorow(X, s):
    """
    Sprawdza, czy macierz X spełnia własność ograniczonej przestrzeni zerowej
    dla każdego podzbioru S o mocy co najwyżej s.

    Argumenty:
    - X: macierz o wymiarach (n, d)
    - s: maksymalna moc podzbioru S

    Działanie:
    - Printuje dla każdego podzbioru S, czy macierz X spełnia własność ograniczonej przestrzeni.
    """
    n, d = X.shape
    wszystkie_kolumny = np.arange(d)  # Indeksy kolumn

    # Funkcja do sprawdzania warunku zdefiniowanego dla zbioru C(S)
    def czy_nalezy_do_C_S(delta, S, S_c):
        delta_S = delta[S]  # Współrzędne odpowiadające S
        delta_S_c = delta[S_c]  # Współrzędne odpowiadające S^c
        return np.linalg.norm(delta_S_c, 1) <= np.linalg.norm(delta_S, 1)

    # Szukanie niezerowych wektorów w jądrze macierzy X
    _, _, VT = np.linalg.svd(X, full_matrices=False)
    jadro_X = VT.T[:, n:]  # Wektory jądra macierzy X (d - n wymiarów)

    # Sprawdzenie dla każdego podzbioru S o mocy co najwyżej s
    for rozmiar in range(1, s + 1):
        for S in itertools.combinations(wszystkie_kolumny, rozmiar):
            S = np.array(S)
            S_c = np.setdiff1d(wszystkie_kolumny, S)  # Komplement zbioru S
            spelnia = True
            for delta in jadro_X.T:
                if not np.allclose(delta, 0) and czy_nalezy_do_C_S(delta, S, S_c):
                    spelnia = False
                    break
            print(f"Podzbiór S: {S}, Spełnia: {spelnia}")


In [3]:
def parametr_niespojnosci_parami(X):
    liczba_wierszy, liczba_kolumn = X.shape  # X to macierz o wymiarach (n, d): n wierszy i d kolumn
    maksymalna_wartosc = float('-inf')
    for kolumna_j in range(liczba_kolumn):
        for kolumna_k in range(liczba_kolumn):
            # Obliczamy iloczyn skalarny kolumn j i k
            iloczyn_skalarny = abs(np.dot(X[:, kolumna_j], X[:, kolumna_k])) / liczba_wierszy
            if kolumna_j == kolumna_k:
                iloczyn_skalarny -= 1  # Odejmujemy 1, jeśli porównujemy ten sam wektor ze sobą
            
            # Aktualizujemy maksymalną wartość o wartość bezwzględną bieżącego obliczenia
            maksymalna_wartosc = max(maksymalna_wartosc, abs(iloczyn_skalarny))
    return maksymalna_wartosc

In [4]:
# Tworzymy losową macierz X (przykład)
macierz_X = np.random.rand(4, 6)  # 4 obserwacje, 6 predyktory
print("Macierz X:", macierz_X)
# Obliczamy średnią dla każdej kolumny
srednie_kolumn = np.mean(macierz_X, axis=0)

# Obliczamy wariancję dla każdej kolumny (przy użyciu N, a nie N-1)
wariancje_kolumn = np.mean((macierz_X - srednie_kolumn)**2, axis=0)

# Standaryzujemy kolumny
macierz_X_zestandaryzowana = (macierz_X - srednie_kolumn) / np.sqrt(wariancje_kolumn)

# Weryfikujemy wyniki
srednie_zestandaryzowanych_kolumn = np.mean(macierz_X_zestandaryzowana, axis=0)  # Średnia zestandaryzowanych kolumn
wariancje_zestandaryzowanych_kolumn = np.mean(macierz_X_zestandaryzowana**2, axis=0)  # Wariancja zestandaryzowanych kolumn

print("Średnia zestandaryzowanych kolumn:", srednie_zestandaryzowanych_kolumn)
print("Wariancja zestandaryzowanych kolumn:", wariancje_zestandaryzowanych_kolumn)
print("Normy L2 kolumn:", np.linalg.norm(macierz_X_zestandaryzowana, ord=2, axis=0))  # Norma L2 kolumn
print("Pierwiastek kwadratowy z liczby obserwacji:", np.sqrt(macierz_X.shape[0]))  # Pierwiastek z liczby obserwacji

Macierz X: [[0.19756521 0.37231716 0.42186394 0.0806728  0.01630351 0.68862539]
 [0.94231326 0.82439536 0.70297355 0.13938733 0.43671085 0.79020366]
 [0.39534747 0.25876544 0.34839068 0.3011056  0.99146217 0.18298142]
 [0.24310748 0.48168904 0.23199446 0.91338536 0.23660644 0.95338769]]
Średnia zestandaryzowanych kolumn: [-1.11022302e-16 -1.90819582e-17  5.55111512e-17  1.11022302e-16
 -5.55111512e-17 -2.22044605e-16]
Wariancja zestandaryzowanych kolumn: [1. 1. 1. 1. 1. 1.]
Normy L2 kolumn: [2. 2. 2. 2. 2. 2.]
Pierwiastek kwadratowy z liczby obserwacji: 2.0


In [5]:
delta_pw = parametr_niespojnosci_parami(macierz_X_zestandaryzowana)

In [6]:
delta_pw

np.float64(0.8833587095582189)

In [7]:
1/(3*2)

0.16666666666666666

In [8]:
wlasnosc_ograniczonej_przestrzeni_dla_podzbiorow(macierz_X_zestandaryzowana, 2)

Podzbiór S: [0], Spełnia: True
Podzbiór S: [1], Spełnia: True
Podzbiór S: [2], Spełnia: True
Podzbiór S: [3], Spełnia: True
Podzbiór S: [4], Spełnia: True
Podzbiór S: [5], Spełnia: True
Podzbiór S: [0 1], Spełnia: True
Podzbiór S: [0 2], Spełnia: True
Podzbiór S: [0 3], Spełnia: True
Podzbiór S: [0 4], Spełnia: True
Podzbiór S: [0 5], Spełnia: True
Podzbiór S: [1 2], Spełnia: True
Podzbiór S: [1 3], Spełnia: True
Podzbiór S: [1 4], Spełnia: True
Podzbiór S: [1 5], Spełnia: True
Podzbiór S: [2 3], Spełnia: True
Podzbiór S: [2 4], Spełnia: True
Podzbiór S: [2 5], Spełnia: True
Podzbiór S: [3 4], Spełnia: True
Podzbiór S: [3 5], Spełnia: True
Podzbiór S: [4 5], Spełnia: True


In [9]:
macierz_X_zla = np.array([
    [1, 0, 3, 0, 1],
    [0, 1, 3, 1, -1],
    [1, 4, 1, 2, -1],
    [0, 1, 3, 1, 1]
])
    

In [11]:
# Obliczamy średnią dla każdej kolumny
srednie_kolumn = np.mean(macierz_X_zla, axis=0)

# Obliczamy wariancję dla każdej kolumny (przy użyciu N, a nie N-1)
wariancje_kolumn = np.mean((macierz_X_zla - srednie_kolumn)**2, axis=0)

# Standaryzujemy kolumny
macierz_X_zla_zestandaryzowana = (macierz_X_zla - srednie_kolumn) / np.sqrt(wariancje_kolumn)

# Weryfikujemy wyniki
srednie_zestandaryzowanych_kolumn = np.mean(macierz_X_zla_zestandaryzowana, axis=0)  # Średnia zestandaryzowanych kolumn
wariancje_zestandaryzowanych_kolumn = np.mean(macierz_X_zla_zestandaryzowana**2, axis=0)  # Wariancja zestandaryzowanych kolumn

print("Średnia zestandaryzowanych kolumn:", srednie_zestandaryzowanych_kolumn)
print("Wariancja zestandaryzowanych kolumn:", wariancje_zestandaryzowanych_kolumn)
print("Normy L2 kolumn:", np.linalg.norm(macierz_X_zla_zestandaryzowana, ord=2, axis=0))  # Norma L2 kolumn
print("Pierwiastek kwadratowy z liczby obserwacji:", np.sqrt(macierz_X_zla.shape[0]))  # 

Średnia zestandaryzowanych kolumn: [0.00000000e+00 4.16333634e-17 2.77555756e-17 0.00000000e+00
 0.00000000e+00]
Wariancja zestandaryzowanych kolumn: [1. 1. 1. 1. 1.]
Normy L2 kolumn: [2. 2. 2. 2. 2.]
Pierwiastek kwadratowy z liczby obserwacji: 2.0


In [12]:
delta_pw_zla = parametr_niespojnosci_parami(macierz_X_zla_zestandaryzowana)

In [13]:
delta_pw_zla

np.float64(0.9622504486493764)